services:
  app:
    build: .
    
    ports:
      - "5000:5000"
    volumes:
      - "./apps:/app/"
  web:
    image: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    depends_on:
      - app

